version: '3.9'

networks:
  database-network:
    driver: bridge

services:
  database:
    image: postgres:14.1-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=meli
      - POSTGRES_PASSWORD=meli2022
    ports:
      - '5432:5432'
    networks:
      - database-network
  server:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    links:
      - database
    image: melidsolartec.azurecr.io/iam_meli
    restart: unless-stopped
    environment:
      - DATABASE_URI=postgres://meli:meli2022@database:5432/postgres?sslmode=disable
      - JWT_KEY=MeLi2022
      - PORT=80
    ports:
      - '80:80'
    networks:
      - database-network
